
% Each camera is first calibrated individually and the intrinsic parameters
% are found. Then two stereo pairs (M-L and M-R) are calibrated together to
% get extrinsic parameters.

% Define square size for all cameras.
squareSize = 10;  % in units of 'millimeters'

%% Calibration for Left Camera

% Define images to process
imageFileNames = {'Calibratie 1\calibrationLeft\Calibratie 1_L_1.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_137.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_273.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_409.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_545.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_681.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_817.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_953.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_1089.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_1225.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_1361.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_1497.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_1633.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_1769.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_1905.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_2041.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_2313.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_2449.jpg',...
    'Calibratie 1\calibrationLeft\Calibratie 1_L_2585.jpg',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsedLeft] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsedLeft);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParamsLeft, imagesUsedLeft, estimationErrorsLeft] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
figure, showReprojectionErrors(cameraParamsLeft); title('Reprojection Errors - Left');

% Visualize pattern locations
figure, showExtrinsics(cameraParamsLeft, 'CameraCentric'); title('Extrinsics - Left');

%% Calibration for Middle Camera

% Define images to process
imageFileNames = {'Calibratie 1\calibrationMiddle\Calibratie 1_M_1.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_137.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_273.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_409.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_545.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_681.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_817.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_953.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_1089.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_1225.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_1361.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_1497.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_1633.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_1769.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_1905.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_2041.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_2177.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_2313.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_2449.jpg',...
    'Calibratie 1\calibrationMiddle\Calibratie 1_M_2585.jpg',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsedMiddle] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsedMiddle);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParamsMiddle, imagesUsedMiddle, estimationErrorsMiddle] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
figure, showReprojectionErrors(cameraParamsMiddle); title('Reprojection Errors - Middle');

% Visualize pattern locations
figure, showExtrinsics(cameraParamsMiddle, 'CameraCentric'); title('Extrinsics - Middle');

%% Calibration for Right Camera

% Define images to process
imageFileNames = {'Calibratie 1\calibrationRight\Calibratie 1_R_1.jpg',...
    'Calibratie 1\calibrationRight\Calibratie 1_R_137.jpg',...
    'Calibratie 1\calibrationRight\Calibratie 1_R_273.jpg',...
    'Calibratie 1\calibrationRight\Calibratie 1_R_409.jpg',...
    'Calibratie 1\calibrationRight\Calibratie 1_R_953.jpg',...
    'Calibratie 1\calibrationRight\Calibratie 1_R_1089.jpg',...
    'Calibratie 1\calibrationRight\Calibratie 1_R_1225.jpg',...
    'Calibratie 1\calibrationRight\Calibratie 1_R_1361.jpg',...
    'Calibratie 1\calibrationRight\Calibratie 1_R_1497.jpg',...
    'Calibratie 1\calibrationRight\Calibratie 1_R_1633.jpg',...
    'Calibratie 1\calibrationRight\Calibratie 1_R_1769.jpg',...
    'Calibratie 1\calibrationRight\Calibratie 1_R_2041.jpg',...
    'Calibratie 1\calibrationRight\Calibratie 1_R_2177.jpg',...
    'Calibratie 1\calibrationRight\Calibratie 1_R_2313.jpg',...
    'Calibratie 1\calibrationRight\Calibratie 1_R_2449.jpg',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsedRight] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsedRight);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParamsRight, imagesUsedRight, estimationErrorsRight] = estimateCameraParameters(...
    imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
figure, showReprojectionErrors(cameraParamsRight); title('Reprojection Errors - Right');

% Visualize pattern locations
figure, showExtrinsics(cameraParamsRight, 'CameraCentric'); title('Extrinsics - Right');

%% Save camera parameters.

save cameraParamsLeft.mat cameraParamsLeft
save cameraParamsMiddle.mat cameraParamsMiddle
save cameraParamsRight.mat cameraParamsRight

%% Stereo Calibration - Middle & Left Cameras

% Define images to process
imageFileNames1 = {'Calibratie 2\calibration2Middle\Calibratie 2_M_1.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_1065.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_1198.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_1331.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_134.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_1464.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_1597.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_1730.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_1863.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_1996.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_2129.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_2262.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_2395.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_2528.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_267.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_400.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_533.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_666.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_799.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_932.jpg',...
    };
imageFileNames2 = {'Calibratie 2\calibration2Left\Calibratie 2_L_1.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_1065.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_1198.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_1331.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_134.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_1464.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_1597.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_1730.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_1863.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_1996.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_2129.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_2262.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_2395.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_2528.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_267.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_400.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_533.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_666.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_799.jpg',...
    'Calibratie 2\calibration2Left\Calibratie 2_L_932.jpg',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames1, imageFileNames2);

% Generate world coordinates of the checkerboard keypoints
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Read one of the images from the first stereo pair
I1 = imread(imageFileNames1{1});

% Create camera intrinsics to be used for calibration

% Check if camera intrinsics object for first camera is still in the workspace
if exist('cameraParamsMiddle', 'var')
    camera1Intrinsics = cameraParamsMiddle;
else
    % Recreate intrinsics from stored parameters
    camera1Intrinsics = cameraIntrinsics([1553.047983, 1548.268145], [533.343491, 484.216000], [1024, 1024], ...
        'RadialDistortion', [-0.179969, 0.123131], ...
        'TangentialDistortion', [0.000000, 0.000000], ...
        'Skew', 0.000000);
end

% Check if camera intrinsics object for second camera is still in the workspace
if exist('cameraParamsLeft', 'var')
    camera2Intrinsics = cameraParamsLeft;
else
    camera2Intrinsics = cameraIntrinsics([1545.883228, 1541.164948], [544.523034, 524.797346], [1024, 1024], ...
        'RadialDistortion', [-0.206282, 0.214159], ...
        'TangentialDistortion', [0.000000, 0.000000], ...
        'Skew', 0.000000);
end

% Calibrate the camera
[stereoParamsLM, pairsUsedLM, estimationErrorsLM] = estimateStereoBaseline(imagePoints, worldPoints, ...
    camera1Intrinsics, camera2Intrinsics, ...
    'WorldUnits', 'millimeters');

% View reprojection errors
figure, showReprojectionErrors(stereoParamsLM); title('Reprojection Errors - Middle + Left');
% Visualize pattern locations
figure, showExtrinsics(stereoParamsLM, 'CameraCentric'); title('Extrinsics - Stereo Middle + Left');


%% Stereo Calibration - Middle & Right Cameras

% Define images to process
imageFileNames1 = {'Calibratie 2\calibration2Middle\Calibratie 2_M_1.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_1065.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_1198.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_134.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_1863.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_1996.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_2129.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_2262.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_2395.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_2528.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_267.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_400.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_533.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_666.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_799.jpg',...
    'Calibratie 2\calibration2Middle\Calibratie 2_M_932.jpg',...
    };
imageFileNames2 = {'Calibratie 2\calibration2Right\Calibratie 2_R_1.jpg',...
    'Calibratie 2\calibration2Right\Calibratie 2_R_1065.jpg',...
    'Calibratie 2\calibration2Right\Calibratie 2_R_1198.jpg',...
    'Calibratie 2\calibration2Right\Calibratie 2_R_134.jpg',...
    'Calibratie 2\calibration2Right\Calibratie 2_R_1863.jpg',...
    'Calibratie 2\calibration2Right\Calibratie 2_R_1996.jpg',...
    'Calibratie 2\calibration2Right\Calibratie 2_R_2129.jpg',...
    'Calibratie 2\calibration2Right\Calibratie 2_R_2262.jpg',...
    'Calibratie 2\calibration2Right\Calibratie 2_R_2395.jpg',...
    'Calibratie 2\calibration2Right\Calibratie 2_R_2528.jpg',...
    'Calibratie 2\calibration2Right\Calibratie 2_R_267.jpg',...
    'Calibratie 2\calibration2Right\Calibratie 2_R_400.jpg',...
    'Calibratie 2\calibration2Right\Calibratie 2_R_533.jpg',...
    'Calibratie 2\calibration2Right\Calibratie 2_R_666.jpg',...
    'Calibratie 2\calibration2Right\Calibratie 2_R_799.jpg',...
    'Calibratie 2\calibration2Right\Calibratie 2_R_932.jpg',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames1, imageFileNames2);

% Generate world coordinates of the checkerboard keypoints
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Read one of the images from the first stereo pair
I1 = imread(imageFileNames1{1});

% Create camera intrinsics to be used for calibration

% Check if camera intrinsics object for first camera is still in the workspace
if exist('cameraParamsMiddle', 'var')
    camera1Intrinsics = cameraParamsMiddle;
else
    % Recreate intrinsics from stored parameters
    camera1Intrinsics = cameraIntrinsics([1553.047983, 1548.268145], [533.343491, 484.216000], [1024, 1024], ...
        'RadialDistortion', [-0.179969, 0.123131], ...
        'TangentialDistortion', [0.000000, 0.000000], ...
        'Skew', 0.000000);
end

% Check if camera intrinsics object for second camera is still in the workspace
if exist('cameraParamsRight', 'var')
    camera2Intrinsics = cameraParamsRight;
else
    camera2Intrinsics = cameraIntrinsics([1559.236176, 1556.783463], [531.335470, 473.973041], [1024, 1024], ...
        'RadialDistortion', [-0.155759, 0.103289], ...
        'TangentialDistortion', [0.000000, 0.000000], ...
        'Skew', 0.000000);
end

% Calibrate the camera
[stereoParamsRM, pairsUsedRM, estimationErrorsRM] = estimateStereoBaseline(imagePoints, worldPoints, ...
    camera1Intrinsics, camera2Intrinsics, ...
    'WorldUnits', 'millimeters');

% View reprojection errors
figure, showReprojectionErrors(stereoParamsRM); title('Reprojection Errors - Middle + Right');
% Visualize pattern locations
figure, showExtrinsics(stereoParamsRM, 'CameraCentric'); title('Extrinsics - Stereo Middle + Right');

%% Save Stereo Params to file.

save stereoParamsLM.mat stereoParamsLM
save stereoParamsRM.mat stereoParamsRM
